version: "3"

services:
  traefik:
     image: "traefik"
     restart: always

     ports:
      - "80:80"
      - "443:443"
     networks:
      - web
     labels:
        - "traefik.enable=true"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.clausin.ga"
        - "traefik.port=8080"
#        - "traefik.frontend.auth.basic=clausi:$$apr1$$Yvjx4.rd$$vC2W6REGit/4KhGJmt/bY."
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/traefik/traefik.toml:/traefik.toml
      - /data/traefik/acme.json:/acme.json
     container_name: traefik
  whoami:
      image: emilevauge/whoami
      networks:
       - web
      labels:
       - "traefik.enable=true"
       - "traefik.backend=whoami"
       - "traefik.frontend.rule=Host:whoami.clausin.ga"
networks:
  web:
    external: true
