version: '3'
services:
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /data/htpc/config/radarr:/config
            - /data/htpc/Movies:/movies
            - /data/htpc/Downloads/complete:/downloads
        env_file: uidgid.env
        labels:
          - 'traefik.enable=true'
          - 'traefik.backend=radarr'
          - 'traefik.port=7878'
        restart: always
        networks:
            - web 

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /data/htpc/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /data/htpc/TV:/tv
            - /data/htpc/Downloads/complete:/downloads
        env_file: uidgid.env
        labels:
            - 'traefik.enable=true'
            - 'traefik.backend:sonarr'
            - 'traefik.port:8989'
        restart: always
        networks:
            - web

    emby:
        image: emby/embyserver
        container_name: emby
        restart: always
        volumes:
            - /data/htpc/emby/config:/config
            - /data/htpc:/media
        ports:
            - 8096:8096
            - 8920:8920
            - 7359:7359/udp
            - 1900:1900/udp
        environment:
            - APP_UID=1000
            - APP_GID=1000
            - TZ='Europe/Berlin'
        labels:
            - 'traefik.backend:emby'
            - 'traefik.enable=true'
            - 'traefik.port=8096'
        networks:
            - web

    deluge:
        image: linuxserver/deluge
        container_name: deluge
        env_file: uidgid.env
        volumes:
            - /data/htpc/Downloads/:/downloads
            - /data/htpc/deluge/config:/config
        restart: always
        ports:
            -  58846:58846
        labels:
            - 'traefik.backend:deluge'
            - 'traefik.enable=true'
            - 'traefik.port=8112'
        networks:
            - web

networks:
   web:
      external: true
